version: "3.4"
services:
  makentu_machine-web:
    container_name: makentu_machine
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8001:8001"
    expose:
      - 8001
    depends_on:
      - postgres
    networks:
      - makentu-competition
      - nginx
  postgres:
    container_name: postgres
    image: postgres
    expose:
      - 5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=MNTU
    networks:
      - makentu-competition
  networks:
    nginx:
      external: true
    makentu-competition:
