import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import HeadBar from "../components/HeadBar";
import { AccountProvider } from "@/context/Account";
import { RequestProvider } from "@/context/Request";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "MakeNTU Machine",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className + " bg-background"}>
        <AccountProvider>
          <RequestProvider>
            <HeadBar />
            {children}
          </RequestProvider>
        </AccountProvider>
      </body>
    </html>
  );
}
